version: '3'
services:
  api:
    environment:
      - FLASK_APP=hello.py
      - FLASK_ENV=development
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    expose:
      - "5000"
    ports:
      - "5000:5000"
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3051:80'
